version: '3'
services:
  node0:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=trace
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zilliqanode0
    command:
      - /zilliqa
      - 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227
    networks:
      localnet:
        ipv4_address: 172.10.10.2

  node1:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=trace
    container_name: zilliqanode1
    image: zq2-node0
    command:
      - /zilliqa
      - 62070b1a3b5b30236e43b4f1bfd617e1af7474635558314d46127a708b9d302e
    networks:
      localnet:
        ipv4_address: 172.10.10.3

  node2:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=trace
    container_name: zilliqanode2
    image: zq2-node0
    command:
      - /zilliqa
      - 56d7a450d75c6ba2706ef71da6ca80143ec4971add9c44d7d129a12fa7d3a364
    networks:
      localnet:
        ipv4_address: 172.10.10.4

  node3:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=trace
    container_name: zilliqanode3
    image: zq2-node0
    command:
      - /zilliqa
      - db670cbff28f4b15297d03fafdab8f5303d68b7591bd59e31eaef215dd0f246a
    networks:
      localnet:
        ipv4_address: 172.10.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.10.0.0/16
