version: '3'
networks:
  zq:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
services:
  node0:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info,opentelemetry=trace,opentelemetry_otlp=trace
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zilliqanode0
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /zilliqa
      - 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227
    ports:
      - "4201:4201"
    networks:
      zq:
        ipv4_address: 10.5.0.10

  node1:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode1
    image: zq2-node0
    volumes:
      - "./infra/config-bootstrap.toml:/config.toml"
    command:
      - /zilliqa
      - 62070b1a3b5b30236e43b4f1bfd617e1af7474635558314d46127a708b9d302e
    networks:
      zq:
        ipv4_address: 10.5.0.11

  node2:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode2
    image: zq2-node0
    volumes:
      - "./infra/config-bootstrap.toml:/config.toml"
    command:
      - /zilliqa
      - 56d7a450d75c6ba2706ef71da6ca80143ec4971add9c44d7d129a12fa7d3a364
    networks:
      zq:
        ipv4_address: 10.5.0.12

  node3:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode3
    image: zq2-node0
    volumes:
      - "./infra/config-bootstrap.toml:/config.toml"
    command:
      - /zilliqa
      - db670cbff28f4b15297d03fafdab8f5303d68b7591bd59e31eaef215dd0f246a
    networks:
      zq:
        ipv4_address: 10.5.0.13

  otterscan:
    environment:
      ERIGON_URL: http://localhost:4201
    image: otterscan/otterscan:develop
    ports:
      - "5100:80"
    # Fast shutdown - Don't gracefully close open connections.
    stop_signal: SIGKILL
