# docker-compsoe file for testing networking with static IPs
version: "3"
services:
  node0:
    depends_on:
      - node2
      - node3 
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    image: zq2-node0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zilliqanode0
    volumes:
      - "./infra/config_docker.toml:/config.toml"
    command:
      - 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227
    ports:
      - "4201:4201"
    networks:
      testnet:
        ipv4_address: 198.51.100.100

  node1:
    depends_on:
      - node2
      - node3
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode1
    image: zq2-node0
    volumes:
      - "./infra/config_docker.toml:/config.toml"
    command:
      - 62070b1a3b5b30236e43b4f1bfd617e1af7474635558314d46127a708b9d302e
    networks:
      testnet:
        ipv4_address: 198.51.100.101

  node2:
    depends_on:
      - node3
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode2
    image: zq2-node0
    volumes:
      - "./infra/config_docker.toml:/config.toml"
    command:
      - 56d7a450d75c6ba2706ef71da6ca80143ec4971add9c44d7d129a12fa7d3a364
    networks:
      testnet:
        ipv4_address: 198.51.100.102

  node3:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode3
    image: zq2-node0
    volumes:
      - "./infra/config_docker.toml:/config.toml"
    command:
      - db670cbff28f4b15297d03fafdab8f5303d68b7591bd59e31eaef215dd0f246a
    networks:
      testnet:
        ipv4_address: 198.51.100.103

  otterscan:
    environment:
      ERIGON_URL: http://localhost:4201
    image: zilliqa/otterscan:develop
    pull_policy: always
    ports:
      - "5100:80"
    networks:
      testnet:
        ipv4_address: 198.51.100.9

  faucet:
    depends_on:
      - node0
    image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa/eth-spout:v1.3.72
    environment:
      RPC_URL: http://node0:4201
      NATIVE_TOKEN_SYMBOL: ZIL
      PRIVATE_KEY: 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227
      ETH_AMOUNT: 100
      EXPLORER_URL: http://localhost:5200
      MINIMUM_SECONDS_BETWEEN_REQUESTS: 60
      BECH32_HRP: zil
    ports:
      - "5200:80"
    # Fast shutdown - Don't gracefully close open connections.
    stop_signal: SIGKILL
    networks:
      testnet:
        ipv4_address: 198.51.100.10

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 198.51.100.0/24
          gateway: 198.51.100.1
