version: '3'
services:
  node0:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info,opentelemetry=trace,opentelemetry_otlp=trace
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zilliqanode0
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /zilliqa
      - 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227
    ports:
      - "4201:4201"

  node1:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode1
    image: zq2-node0
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /zilliqa
      - 62070b1a3b5b30236e43b4f1bfd617e1af7474635558314d46127a708b9d302e

  node2:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode2
    image: zq2-node0
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /zilliqa
      - 56d7a450d75c6ba2706ef71da6ca80143ec4971add9c44d7d129a12fa7d3a364

  node3:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: zilliqa=info
    container_name: zilliqanode3
    image: zq2-node0
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /zilliqa
      - db670cbff28f4b15297d03fafdab8f5303d68b7591bd59e31eaef215dd0f246a

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./infra/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  mimir:
    image: grafana/mimir:latest
    volumes:
      - "./infra/mimir.yaml:/etc/mimir/config.yaml"
    command:
      - "./mimir"
      - "--config.file"
      - "/etc/mimir/config.yaml"
    ports:
      - "9009:9009"
  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  otterscan:
    environment:
      ERIGON_URL: http://localhost:4201
    image: otterscan/otterscan:develop
    ports:
      - "5100:80"
