[profile.default]
src = "src"
out = "out"
libs = [
  "../../vendor/openzeppelin-contracts/node_modules",
  "../../vendor/openzeppelin-contracts/lib" ]
remappings = [
  "@openzeppelin/=../../vendor/openzeppelin-contracts/node_modules/@openzeppelin/",
  "contracts/=src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
