[profile.default]
src = "src"
out = "out"
libs = [
  "../../vendor/openzeppelin-contracts/contracts",
  "../../vendor/openzeppelin-contracts/lib"
]
test = 'test'
cache_path = 'cache-foundry'
via_ir = true
auto_detect_solc = true
build_info = true
remappings = [
  "@openzeppelin/=../../vendor/openzeppelin-contracts/",
  "contracts/=src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
