[profile.default]
src = "src"
out = "out"
libs = [
  "../../vendor/openzeppelin-contracts/contracts",
  "../../vendor/openzeppelin-contracts/lib"
]
remappings = [
  "@openzeppelin/=../../vendor/openzeppelin-contracts/",
  "contracts/=src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
