formatter: "markdown"
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
settings:
  indent: 2
content: |-
  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}