---
# GCP Configuration
ansible_ssh_args: --tunnel-through-iap --zone={{ zone }} --no-user-output-enabled
ansible_scp_extra_args: --tunnel-through-iap --zone={{ zone }} --quiet

# Node Configuration
eth_chain_id: 33103
chain_name: "zq2-prototestnet"
dns_subdomain: "zq2-prototestnet.zilliqa.com"
project_id: prj-d-zq2-testnet-g13pnaa8
log_level: "zilliqa=trace"
enable_faucet: true

# Docker images
zq2_image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/zq2:v0.9.3
otterscan_image: zilliqa/otterscan:develop
spout_image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/eth-spout:main
stats_dashboard_image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/zilstats-server:v0.0.6
stats_agent_image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/zilstats-agent:v0.0.6
zq2_metrics_image: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-private/zq2-metrics:v0.0.1
process_exporter_image: ncabatoff/process-exporter:0.8.1
node_exporter_image: prom/node-exporter:v1.9.0

# Persistence Configuration
persistence_dir: "/data"
persistence_url: ""
checkpoint_url: ""

# KMS Configuration
enable_kms: false
kms_project_id: "{{ 'prj-p-kms-2vduab0g' if project_id.startswith('prj-p') else 'prj-d-kms-tw1xyxbh' }}"
