---
- name: Create Docker config directory
  file:
    path: /root/.docker
    state: directory
    mode: '0700'

- name: Configure Docker registry authentication
  shell: |
    gcloud auth configure-docker {{ docker_registry }} --quiet
  args:
    creates: /root/.docker/config.json

- name: Ensure Docker registry authentication is working
  shell: docker login {{ docker_registry }} --quiet
  register: docker_login
  changed_when: false
  failed_when: docker_login.rc != 0 