---
- name: Install and configure healthcheck service
  hosts: role_bootstrap:role_validator
  become: true

  tasks:



- name: Create checkpoint directory
  file:
    path: /var/lib/zilliqa/checkpoint
    state: directory
    mode: '0755'

- name: Download checkpoint data
  shell: |
    gsutil cp {{ checkpoint_url }} /var/lib/zilliqa/checkpoint/checkpoint.tar.gz
  args:
    creates: /var/lib/zilliqa/checkpoint/checkpoint.tar.gz

- name: Extract checkpoint data
  unarchive:
    src: /var/lib/zilliqa/checkpoint/checkpoint.tar.gz
    dest: /var/lib/zilliqa/checkpoint
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not ansible_check_mode 