[package]
name = "deployer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
clap = { version = "4.4.18", features = ["derive"] }
git2 = "0.18.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.113"
tempfile = "3.9.0"
toml = "0.8.8"
