usage_stats:
  enabled: false

multitenancy_enabled: false

memberlist:
  bind_port: 7946
  advertise_addr: 0.0.0.0
  join_members:
    - 0.0.0.0:7946

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 9009
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1
