---
- name: Configure log rotation
  hosts: all:!role_apps
  become: true

  tasks:
    - name: Create logrotate configuration
      template:
        src: templates/zilliqa_logrotate.j2
        dest: /etc/logrotate.d/zilliqa
        mode: '0644'
