---
- name: Download Zilliqa node persistence
  hosts: all:!role_apps
  become: true
  tags:
    - install
    - all

  tasks:

    - name: Check if Zilliqa service exists
      ansible.builtin.stat:
        path: "/etc/systemd/system/zilliqa.service"
      register: service_file

    - name: Stop Zilliqa service
      ansible.builtin.systemd:
        name: zilliqa
        state: stopped
      when: service_file.stat.exists

    - name: Clean persistence directory
      ansible.builtin.file:
        path: "{{ persistence_dir }}"
        state: absent

    - name: Create persistence directory
      ansible.builtin.file:
        path: "{{ persistence_dir }}"
        state: directory
        owner: zilliqa
        group: zilliqa
        mode: '0755'

    - name: Download and extract tar.gz file
      when: persistence_url != "" and persistence_url.endswith('.tar.gz')
      block:
        - name: Download tar.gz file
          ansible.builtin.shell:
            cmd: "gsutil -m cp {{ persistence_url }} {{ persistence_dir }}/{{ persistence_url | basename }}"
            chdir: "{{ persistence_dir }}"
          register: download_result

        - name: Extract tar.gz file
          ansible.builtin.unarchive:
            src: "{{ persistence_dir }}/{{ persistence_url | basename }}"
            dest: "{{ persistence_dir }}"
            remote_src: true

        - name: Remove downloaded tar.gz file
          ansible.builtin.file:
            path: "{{ persistence_dir }}/{{ persistence_url | basename }}"
            state: absent

    - name: Download persistence folder
      ansible.builtin.shell:
        cmd: "gsutil -m cp -r {{ persistence_url }}/* {{ persistence_dir }}"
      when: persistence_url != "" and not persistence_url.endswith('.tar.gz') 
