---
- name: Install and configure Persistence Backup
  hosts: role_persistence
  become: true
  tags:
    - install
    - all

  tasks:

    - name: Install required Python packages
      ansible.builtin.pip:
        name:
          - google-cloud-storage
          - google-cloud-logging
          - requests
        state: present

    - name: Create persistence backup script
      ansible.builtin.template:
        src: templates/persistence.py.j2
        dest: /usr/local/bin/persistence.py
        mode: '0755'
      notify:
        - Restart Persistence Backup

    - name: Ensure /opt/zilliqa exists
      ansible.builtin.file:
        path: /opt/zilliqa
        state: directory
        mode: '0755'

    - name: Ensure /var/run/zilliqa exists
      ansible.builtin.file:
        path: /var/run/zilliqa
        state: directory
        mode: '0755'

    - name: Deploy persistence backup systemd service
      ansible.builtin.template:
        src: templates/persistence.service.j2
        dest: /etc/systemd/system/persistence.service
        mode: '0644'
      notify:
        - Restart Persistence Backup

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Start and enable persistence backup
      systemd:
        name: persistence.service
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart Persistence Backup
      systemd:
        name: persistence.service
        state: restarted
        enabled: yes
        daemon_reload: yes
