---
- name: Install and configure ZQ2 Metrics
  hosts: private_api_metrics
  become: true
  tags:
    - install
    - all

  tasks:

    - name: Extract version tag from zq2_metrics_image
      set_fact:
        zq2_metrics_version: "{{ zq2_metrics_image.split(':')[-1] }}"

    - name: Show extracted version
      debug:
        var: zq2_metrics_version

    - name: Create ZQ2 Metrics script
      template:
        src: templates/zq2_metrics.sh.j2
        dest: /usr/local/bin/zq2_metrics-{{ zq2_metrics_version }}.sh
        mode: '0777'
      vars:
        zq2_metrics_version: "{{ zq2_metrics_version }}"
      notify:
        - Restart ZQ2 Metrics service

    - name: Force create symlink for zq2_metrics script
      ansible.builtin.file:
        src: /usr/local/bin/zq2_metrics-{{ zq2_metrics_version }}.sh
        dest: /usr/local/bin/zq2_metrics.sh
        state: link
        force: true
      notify:
        - Restart ZQ2 Metrics service

    - name: Create ZQ2 Metrics systemd service
      template:
        src: templates/zq2_metrics.service.j2
        dest: /etc/systemd/system/zq2_metrics.service
        mode: '0644'
      notify:
        - Restart ZQ2 Metrics service
    
    - name: Force create symlink for zq2_metrics service
      ansible.builtin.file:
        src: /etc/systemd/system/zq2_metrics.service
        dest: /etc/systemd/system/multi-user.target.wants/zq2_metrics.service
        state: link
        force: true
      notify:
        - Restart ZQ2 Metrics service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Start and enable node service
      systemd:
        name: zq2_metrics
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart ZQ2 Metrics service
      systemd:
        name: zq2_metrics
        state: restarted
        enabled: yes
        daemon_reload: yes 