---
- name: Install and configure Stats Agent
  hosts: role_api:role_bootstrap:role_validator:private_api_gzil
  become: true
  tags:
    - install
    - all

  tasks:

    - name: Extract version tag from stats_agent_image
      set_fact:
        stats_agent_version: "{{ stats_agent_image.split(':')[-1] }}"

    - name: Show extracted version
      debug:
        var: stats_agent_version

    - name: Retrieve stats dashboard key KMS decrypted
      shell: |
        gcloud secrets versions access latest --project="{{ project_id }}" --secret="{{ chain_name }}-stats-dashboard-enckey" | base64 -d | gcloud kms decrypt --ciphertext-file=- --plaintext-file=- --key="{{ chain_name }}-stats-dashboard" --keyring="kms-{{ chain_name }}" --location=global --project="{{ kms_project_id }}"
      register: retrieved_stats_dashboard_key
      when: enable_kms

    - name: Set fact with stats dashboard key KMS decrypted
      set_fact:
        stats_dashboard_key: "{{ retrieved_stats_dashboard_key.stdout }}"
      when: enable_kms

    - name: Retrieve stats dashboard key
      shell: |
        gcloud secrets versions access latest --project="{{ project_id }}" --secret="{{ chain_name }}-stats-dashboard"
      register: retrieved_stats_dashboard_key
      when: not enable_kms

    - name: Set fact with stats dashboard key
      set_fact:
        stats_dashboard_key: "{{ retrieved_stats_dashboard_key.stdout }}"
      when: not enable_kms

    - name: Create Stats Agent script
      template:
        src: templates/stats_agent.sh.j2
        dest: /usr/local/bin/stats_agent-{{ stats_agent_version }}.sh
        mode: '0777'
      vars:
        stats_agent_version: "{{ stats_agent_version }}"
        stats_dashboard_key: "{{ stats_dashboard_key }}"
      notify:
        - Restart Stats Agent service
    
    - name: Force create symlink for stats_agent script
      ansible.builtin.file:
        src: /usr/local/bin/stats_agent-{{ stats_agent_version }}.sh
        dest: /usr/local/bin/stats_agent.sh
        state: link
        force: true
      notify:
        - Restart Stats Agent service

    - name: Create Stats Agent systemd service
      template:
        src: templates/stats_agent.service.j2
        dest: /etc/systemd/system/stats_agent.service
        mode: '0644'
      notify:
        - Restart Stats Agent service
    
    - name: Force create symlink for stats_agent service
      ansible.builtin.file:
        src: /etc/systemd/system/stats_agent.service
        dest: /etc/systemd/system/multi-user.target.wants/stats_agent.service
        state: link
        force: true
      notify:
        - Restart Stats Agent service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Start and enable node service
      systemd:
        name: stats_agent
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Restart Stats Agent service
      systemd:
        name: stats_agent
        state: restarted
        enabled: yes
        daemon_reload: yes 