name: ZQ2 Security audit
on:
  pull_request:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for high and critical vulnerabilities on deps
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ github.token }}
