name: ZQ2 Security audit
on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for high and critical vulnerabilities on deps
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ github.token }}
