name: Zilliqa 2 Load Test

on:
  push:
    branches:
      - '**'  # Run on push to any branch
  workflow_dispatch: # Allows manual triggering with inputs
    inputs:
      rpc_endpoint:
        description: 'Zilliqa 2 RPC Endpoint (e.g., https://api.zq2-devnet.zilliqa.com)'
        required: true
        default: 'https://api.zq2-devnet.zilliqa.com'

env:
  RPC_ENDPOINT: ${{ github.event.inputs.rpc_endpoint || 'https://api.zq2-devnet.zilliqa.com' }}

jobs:
  execute_load_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # sender_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        sender_id: [1, 2]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Scripting Language (e.g., Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create and Fund Test Account
        id: create_account
        env:
          FAUCET_PRIVATE_KEY: ${{ secrets.FAUCET_PRIVATE_KEY }}
        run: |
          echo "Preparing test account..."
          chmod +x ./scripts/*.sh
          ./scripts/prepare_accounts.sh \
            --num-accounts 1 \
            --faucet-pk "${{ env.FAUCET_PRIVATE_KEY }}" \
            --rpc-endpoint "${{ env.RPC_ENDPOINT }}" \
            --output-dir ./prepared_test_accounts
          echo "Account preparation finished."

      - name: Run Load Test
        run: |
          echo "Starting Load Test..."
          mkdir -p ./sender_logs
          ./scripts/run_zilliqa_load_test.sh \
            --rpc-endpoint "${{ env.RPC_ENDPOINT }}" \
            --accounts-dir ./prepared_test_accounts \
            --log-dir ./sender_logs
          echo "Load Test Finished"
