[package]
name = "evm_ds"
version = "0.1.0"
edition = "2021"
rust-version = "1.61"

[lib]
name = "evm_ds"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.56", default-features = false }
async-scoped = { version = "0.7", features = ["use-tokio"] }
base64 = "0.13.0"
byteorder = "1.4.3"
bytes = "1.1.0"
clap = { version = "3.1.6", features = ["derive"] }
ethabi = "18.0.0"
ethereum = "0.12.0"
evm = { git = "https://github.com/Zilliqa/evm", rev = "ef7a9d1476f15660aad98dec5275beae016e83e4", features = ["tracing"] }
ethers = "2.0.7"
futures = { version = "0.3.21", features = ["executor", "thread-pool"] }
hex = "0.4"
libsecp256k1 = "0.7.0"
num-bigint = "0.4"
num-integer = "0.1.45"
parity-tokio-ipc = "0.9"
primitive-types = { version = "0.12", features = ["serde"] }
protobuf = { version = "2.27.1",  features = ["with-bytes"] }
ripemd = "0.1.3"
serde = "1.0.152"
serde_cbor = "0.11.2"
serde_json = "1.0.91"
serde_yaml = "0.8.25"
sha2 = "0.10.6"
sha3 = "0.10.1"
tokio = { version = "1.17", features = ["full"] }
witnet-bn = "0.4.5"
tracing = "0.1.37"

[build-dependencies]
protoc-rust = "2"
